@startuml cdu_001.puml
title CDU 001 - Login

actor Visitante

participant IndexUI
participant LoginUI
participant UsuarioController
participant UsuarioDAO
participant Usuario
database SQLite

IndexUI -> LoginUI: main()

Visitante -> LoginUI: preencher email, senha, perfil
Visitante -> LoginUI: clicar "Entrar"

LoginUI -> UsuarioController: autenticar(email, senha)

activate UsuarioDAO
UsuarioController -> UsuarioDAO: autenticar(email, senha)
UsuarioDAO -> UsuarioDAO: abrir()
UsuarioDAO -> SQLite: SELECT * FROM usuario\nWHERE email=? AND senha=?
SQLite --> UsuarioDAO: row | null
UsuarioDAO -> Usuario: Usuario(**row)
UsuarioDAO -> UsuarioDAO: fechar()
deactivate UsuarioDAO

UsuarioDAO --> UsuarioController: Usuario | None
UsuarioController --> LoginUI: Usuario | None

@enduml
