@startuml cdu_002_registrar_objet0
title CDU 002 - Registrar Objeto

actor Funcionario

participant IndexUI
participant RegistrarObjetoUI
participant ObjetoController
participant ObjetoDAO
participant Objeto
database SQLite

IndexUI -> RegistrarObjetoUI: main()

Funcionario -> RegistrarObjetoUI: preencher descricao,\nlocal, data, hora
Funcionario -> RegistrarObjetoUI: clicar "Registrar Objeto"

RegistrarObjetoUI -> ObjetoController: inserir(descricao, data_hora_encontrado, local_encontrado)

ObjetoController -> Objeto: __new__(descricao, data_hora_encontrado, local_encontrado)

ObjetoController -> ObjetoDAO: inserir(objeto)

activate ObjetoDAO
ObjetoDAO -> ObjetoDAO: abrir()
ObjetoDAO -> SQLite: INSERT INTO objeto\n(descricao, data_hora_encontrado, local_encontrado)
ObjetoDAO -> SQLite: SELECT * FROM objeto\nWHERE id = lastrowid
SQLite --> ObjetoDAO: row
ObjetoDAO -> Objeto: Objeto(**row)
ObjetoDAO -> ObjetoDAO: fechar()
deactivate ObjetoDAO

ObjetoDAO --> ObjetoController: Objeto
ObjetoController --> RegistrarObjetoUI: sucesso | excecao
RegistrarObjetoUI --> Funcionario: mensagem de sucesso\nou erro

@enduml
